### ISSUE TITLE
Determine scalability limits and improvements

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1164]
/kind feature

**Describe the solution you'd like**
#1163 proposes to increase the default concurrency limit for EC2 instance
reconciliation. For this PR, @rudoi reported that New Relic set the concurrency limit to 12 for their clusters (which are self-managed).

A test plan should be developed to determine a sensible default for concurrency limits, combined with feedback from end users of Cluster API and other lifecycle managers covering 80% of users if possible.

Ideally, this work should be supplemented with improvements to the handling of API limits.

**Comment by egernst** [comment]
Some initial feedback:
- a higher limit definitely makes sense, otherwise you're waiting all day. I'm not sure the downside of having a higher number, but I've tested with concurrency 100 and 256 without any real issues.
- the real limiting for scaling in these scenarios are the token's time limit.  When scaling, we see that the tokens are created early on, AWS provides machines at a reasonable rate, and the Kubernetes control plane slowly catches up. The current default token resaults in failed kubeadm join's due to invalid tokens.  This is very limiting (I see that a PR is in place to make this configurable - I would like to understand downside of having a longer period of time as the default - isn't kubeadm default 24h?).

**Comment by randomvariable** [comment]
I think ideally we'd have very short-lived tokens that were used only once per machine, but the post v1alpha1 data model makes that slightly awkward.

Downside of long-lived tokens is that someone scraping the metadata endpoint can register themselves as nodes.

**Comment by egernst** [comment]
> I think ideally we'd have very short-lived tokens that were used only once per machine, but the post v1alpha1 data model makes that slightly awkward.
> 

The hard part for 'very short lived' is the delay between creation and that 800th node trying to register itself. 

> Downside of long-lived tokens is that someone scraping the metadata endpoint can register themselves as nodes.

Understand.

**Comment by ncdc** [comment]
In #1308 we did increase the concurrency levels.

Trying to de-scope v0.5. This is important but not a release blocker.

/remove-lifecycle stale
/priority important-longterm
/remove-priority important-soon
/milestone Next

**Comment by randomvariable** [comment]
This was done.
/close
