### ISSUE TITLE
Deletes are too slow

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#1328]
/kind bug

**What steps did you take and what happened:**
It took over 5 minutes to delete a 3 node control plane cluster is too slow. I expect we should be reconciling on deletes more quickly.

I looked at the logs and it seems to be the EIP is not releasing. It took over 4 minutes just to release the EIP. If that's just how AWS works then there's not much we can do.

**What did you expect to happen:**
I expect deleting a 3 node cluster to take less time than 5 minutes.

**Comment by detiber** [comment]
There are a few blockers here...  
1) Termination of the instances takes quite a bit of time (I believe due to waiting for services to stop during the shutdown request and we might be able to improve this behavior)
2) NAT Gateway and associated EIP deletion takes a while (not much we can do about this one)

**Comment by randomvariable** [comment]
That is how AWS works. Some parallisation has been added in the meantime.

/close
