### ISSUE TITLE
Allow bastion host to use user specified image

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#1441]
/kind feature

**Describe the solution you'd like**
Allow bastion host to use user specified image even in the managed mode. I can use my images for control plane and worker nodes today but not bastion host in managed mode. 

**Environment:**

- Cluster-api-provider-aws version: 0.4.6

**Comment by ncdc** [comment]
As @vincepri pointed out, we probably will need to expose the user data for the VM (a ref to a Secret?) with a fallback to our default script, because there's no guarantee that the default script will work with any arbitrary AMI.

From a design standpoint, I would probably add fields to AWSCluster: BastionImageID and BastionImageUserDataSecretName (wordsmith). For each field, if it is "", fall back to the default value currently being used.

**Comment by detiber** [comment]
Alternatively we could add a flag to disable creation of the bastion and suggest users use Session Manager for accessing instances directly instead of tunneling through a bastion: https://aws.amazon.com/about-aws/whats-new/2019/07/session-manager-launches-tunneling-support-for-ssh-and-scp/

**Comment by ncdc** [comment]
@vivgoyal you found a workaround for this, right?

**Comment by ncdc** [comment]
We are moving away from the bastion image and want to switch to AWS SSM. Is it ok to close this?

**Comment by voor** [comment]
AWS SSM is not available in all AWS regions currently, and the regions where it's not available are not covered by the current hard-coded Bastion AMI images, so those areas are currently unable to leverage any of this functionality.

**Comment by ncdc** [comment]
Ok, let's keep it open. Thanks for checking!

My recommendation is to allow the user to specify an AMI and a bootstrap data secret name (both optional).

As @randomvariable suggested in Slack, we could also move the bastion AMI defaulting logic into a webhook.

Another idea to consider: we could allow user overrides of bastion AMIs with an optional ConfigMap (key=region, value=ami).

**Comment by bagnaram** [comment]
I like the idea of a ConfigMap because it enables the addition of custom regions having their own AMI. I am thinking along the lines of GovCloud, c2s, custom regions.

**Comment by detiber** [comment]
Should we also consider the idea of having a default lookup pattern and provide orgID and pattern overrides similar to what we are doing with Machines?

**Comment by ncdc** [comment]
Would we want to do both, or just one of these options?

**Comment by detiber** [comment]
I think all three options have value for different use cases:
- AMI ID for quick and dirty, don't really care about multiple regions
- OrganizationID for when using a pre-validated copy of the default ubuntu/al2/whatever image we use by default (not sure off the top of my head) but don't want to worry about having to deal with Regions
- OrgainizationID/pattern for when building org-specific images.

Now that I've enumerated that, maybe the second scenario of overriding the OrgID without providing a pattern might not be needed, since if they are copying the image anyway they might as well provide a pattern to match it.

**Comment by randomvariable** [comment]
@evalsocket thanks for taking it! If you don't mind, just ping in here with "/lifecycle active" if you start work on it to block anyone else accidentally stepping on your toes.

**Comment by fyangd** [comment]
Any movement on this issue?

To add some user perspective on the relevance of this issue, deploying a management cluster on AWS govCloud env fails with a perplexing error message:

```
0724 20:42:21.937375       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile bastion host for AWSCluster tkg-system/tkg-mgmt-aws: failed to run instance: InvalidAMIID.Malformed: Invalid id: \"unknown region\" (expecting \"ami-...\")\n\tstatus code: 400, request id: 406bc73a-2d37-486d-a953-7c6e50469c3e"  "controller"="awscluster" "request"={"Namespace":"tkg-system","Name":"tkg-mgmt-aws"}
```

Because bastion host is enabled by default, fixing this issue or warning users that bastion host is about to deployed to a non-supported region would be very helpful!
