### ISSUE TITLE
Support clusterctl by implementing provider contract

### ISSUE THREAD

**Issue by wfernandes** [kubernetes-sigs/cluster-api-provider-aws#1500]
/kind feature

**Describe the solution you'd like**
After following instructions [in the quickstart](https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html)
I get the following error when running `clusterctl config cluster my-cluster`
```
$ clusterctl config cluster my-cluster --infrastructure=aws:v0.5.0
Error: failed to read "config-kubeadm.yaml" from provider's repository "aws": failed to get GitHub release v0.5.0: failed to read release "v0.5.0": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-aws/releases/tags/v0.5.0: 404 Not Found []
```
I'm using `clusterctl-settings.json`.
```
{
      "providers": [ "cluster-api", "kubeadm-bootstrap", "aws"],
      "provider_repos": ["../cluster-api-provider-aws"]
}
```

We need to follow the [provider contract and provide the workload cluster template](https://master.cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#workload-cluster-templates) `config-kubeadm.yaml`

**Environment:**
- Cluster-api version: https://github.com/kubernetes-sigs/cluster-api/tree/7816c0c01a97824103a2ee8fa8078625f0d56d36
- Cluster-api-provider-aws version: 00d21035bb4d0ea3fd49a77ffd5811529abeaa3b

**Comment by rudoi** [comment]
/assign
/lifecycle active

working on this with @mytunguyen

**Comment by rudoi** [comment]
@wfernandes, some quick questions:

- CAPA has a bunch of examples YAML already, but the available env vars don't quite add up. Were you thinking this should be held completely separate from those? 
- Should the local hack script be updated as part of this issue to support fetching these default templates locally?

**Comment by wfernandes** [comment]
@rudoi Sorry for the late response. I'm still trying to learn the intricacies of clusterctl.  @fabriziopandini can hopefully provide some insight into what the provider contract expects from `config-kubeadm.yaml`.

**Comment by fabriziopandini** [comment]
> CAPA has a bunch of examples YAML already, but the available env vars don't quite add up.

From a certain point of view, clusterctl is an effort to standardize some behaviors across providers.
Said that it is up to providers to choose if to provide cluster templates for clusterctl, if to provide the user a different approach for generating YAML, or both.  

I'm personally for converging as much as possible because this was the goal of the community effort around clusterctl v2, but I have some bias here. 

FYI. As far as I know, CAPV is going to sunset its own YAML generator.
 
> Should the local hack script be updated as part of this issue to support fetching these default templates locally? 

I'm +1 for this because it will provide a better developer experience (if we can find a generic approach that works across providers).

However, it is important to understand that the local hack script can be a replacement of the previous point, that instead is related to what kind of templates are going to be added to the release package

**Comment by randomvariable** [comment]
Is anyone working on this at present, if not, I can pick this up?

**Comment by rudoi** [comment]
/unassign

@randomvariable all yours!
