### ISSUE TITLE
AWS account multitenancy using a single instance of the controller

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#1552]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
At present, CAPA relies on the default authentication providers within the AWS SDK.
The principle is described in the Java SDK at https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html, with the Go SDK supporting the following chain:

1. If `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_IAM_ROLE_ARN` env vars are both set, use refreshable role assumption via OIDC federation (v1alpha3 onwards).
2. Environment Variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, etc...)
3. Shared credentials file specified by `AWS_SHARED_CREDENTIALS_FILE` environment variable (defaulting to ~/.aws/config)
4. ECS refreshable credentials from the URL specified in the `AWS_CONTAINER_CREDENTIALS_FULL_URI` env var, using the env var `AWS_CONTAINER_AUTHORIZATION_TOKEN` as the authorisation header
5. ECS refreshable credentials from `http://169.254.170.2/${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}`
6. EC2 metadata

In addition, the [shared credentials file supports a wide variety of combinations](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).

This provides maximum flexibility in the provision of credentials. In practice, this is implemented in CAPA by not specifying any credential parameters.

However, this means that a separate instance of CAPA must exist for each account/role/user that CAPA is meant to manage a cluster under, which may affect the deployment of conversion & defaulting webhooks as well as placing a scalability limit on running CAPA.

If possible, CAPA could support multi-tenancy within a single instance whilst preserving flexibility in terms of the authentication methods on offer.

We can break the above authentication methods into the following categories:

1. Forms of static credential provisioning
     * Env vars and static credentials encoded in the shared configuration file
2. Dynamic retrieval of credentials from a URL
     * ECS & EC2 IMDS metadata
3. Role assumption
     * Faked EC2 IMDS metadata provided by a system like Kiam
     * OIDC federation
     * Shared configuration file specifying role assumption in a profile with a static or dynamic EC2 metadata source

2 is specific to processes running on EC2 hosts or on ECS, and is not relevant, leaving 1 & 3 as methods which should be supportable for multi-tenancy within a single process.

From a Kubernetes perspective, any supply of credentials should be secured - if it comes from an API server resource, that API server resource must have appropriate RBAC (use of secret references, restricted CRD etc...).

**Comment by sethp-nr** [comment]
For our "soft" multi-tenancy use cases I think we would get pretty far by adding a "profileName" field to the various AWS resources and passing that in when we're creating clients for talking to AWS.

Would that + some degree of validating webhook for what `profileName`s are permitted in a given namespace be a useful tool here?

**Comment by randomvariable** [comment]
As one of the options that's supported, yes. I think this probably needs to be CAEP'd as its security sensitive. Happy to work on a proposal.

**Comment by andrewmyhre** [comment]
We're targeting exactly this capability in our organization because we want to target small AWS accounts for individual divisions managed by CAPI host clusters in separate accounts. 

The approved strategy of obtaining credentials in our organization's AWS architecture is for processes to use `sts assume-role` when they need to credential hop. Kiam is well suited to our needs generally, and in this case we'll want to replicate that behavior within CAPA.

The approach I'd considering was adding an optional field `IAMRoleARN` to the `AWSCluster` _and_ `AWSMachineTemplate` and `AWSMachine` types. I would update the reconciliation process to new up an AWS client per reconciliation (assuming it doesn't already do this? haven't looked) and use the scoped IAM role ARN if provided. If no IAM role is provided the controllers would still new up a client per reconcile, they just wouldn't attempt a role assumption.

Reading the OP though I may not be thinking broadly enough. Understand we're under some time constraints to have this capability working at the scope I described above. I'd like to provide this implementation in such a way that other authentication methods could be substituted in the flow. I'm not familiar with "OIDC federation" as it relates to _IAM roles_. We were planning to start implementing this next week, so I'd be happy to contribute an implementation of the approach I've described, and I'd like to understand the requirements better from the SIG's point of view so I don't contribute something that limits future capabilities.

**Comment by sethp-nr** [comment]
FWIW the approach you describe would solve our use cases as well. Up-thread @randomvariable asked that we follow the CAEP process regarding that, which would offer an opportunity to collect feedback from folks using a authentication different model – how does that sound to you?

It doesn't look like we have CAEPs in this repo yet, and I don't see provider-specific CAEPs upstream, so I think that would look something like [copy the template doc](https://github.com/kubernetes-sigs/cluster-api/blob/0b70358551c437ae7e695a207d438b903276c601/docs/proposals/YYYYMMDD-template.md) into a new `docs/proposals` directory in this repo, and we start following it for adding in the kind of role assumption flow you're describing.

**Comment by andrewmyhre** [comment]
Proposal doc: https://docs.google.com/document/d/1vwjvWc-RIZfwDXb-3tW4gKBOaPCKhripfhXshOmB5z4/edit#
