### ISSUE TITLE
Accept provided VPC infrastructure with only a private subnet

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api-provider-aws#1696]
/kind feature

As a user, I may want to provide CAPA with a VPC that has no associated public subnets or internet gateways. It is unclear whether CAPA would support this today, even with an `internal` load balancing scheme for the apiserver.

**Anything else you would like to add:**

The current subnet code may issue an error when reconciling an unmanaged VPC with no public subnets: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/99349b8abeb34123b2e13d025946a2e66d6d6b40/pkg/cloud/services/ec2/subnets.go#L77-L87

I can't find anywhere else we mandate public subnets outside of points-of-use, and it looks like we may not even hit that check if the VPC has more than one subnet in it. More testing would be required to validate CAPA's behavior in this scenario.

**Comment by vincepri** [comment]
If I understood this correctly, the fix should be to allow to have unmanaged scenarios to have no public subnets at all.

We should basically ignore and not return an error on line 79, unless I missed something?

**Comment by randomvariable** [comment]
That sounds correct.

**Comment by bagnaram** [comment]
The bastion also expects public/private subnets to be available and we may see scenarios of VPC pairing in disconnected environments and it gets more tricky in this case.

**Comment by sethp-nr** [comment]
I don't believe we spin up a bastion in an unmanaged VPC – the idea is that telling CAPA which VPC to use means you're comfortable with the tradeoffs of setting up and managing a VPC yourself.

**Comment by richardcase** [comment]
I have tested this by removing the public subnet check in #1721 and specifying subnets that are private (i.e. they don't have a route to a IGW).

It breaks on ELB creation as the default is to have an internet facing elb:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/elb/loadbalancer.go#L57

We can specify the internal scheme by using: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awscluster_types.go#L98

And also we could update the default scheme: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/scope/cluster.go#L178
so that it checks for the number of public subnets. Perhaps something like this:

```
func (s *ClusterScope) ControlPlaneLoadBalancerScheme() infrav1.ClassicELBScheme {
	if s.ControlPlaneLoadBalancer() != nil && s.ControlPlaneLoadBalancer().Scheme != nil {
		return *s.ControlPlaneLoadBalancer().Scheme
	}
	if len(s.Subnets().FilterPublic()) > 0 {
		return infrav1.ClassicELBSchemeInternetFacing
	}

	return infrav1.ClassicELBSchemeInternal
}
```
By making these changes it appears to have created the cluster ok. But on deletion there where a few issues.....which i think would be fairly easy to fix

**Comment by sethp-nr** [comment]
> It breaks on ELB creation as the default is to have an internet facing elb

IMO it's perfectly fine to throw an Event saying "couldn't find public subnets for ELB" if that's what was asked for – even if it was asked implicitly by way of a default. We could consider changing the error message to say "here's the load balancer scheme field you might want to look at"?  Changing the default based on the availability of public subnets works well too, though it provides slightly worse feedback in the case where the humans _intended_ to supply public subnets but, for whatever reason, didn't.

**Comment by andrewmyhre** [comment]
@richardcase let me know if I can help with the work you started to address this

**Comment by evalsocket** [comment]
@sethp-nr  I just created a PR for spin up a bastion in an unmanaged VPC if it's enabled in the spec, regardless of managed or unmanaged VPC. 
Check Issue  #1748
