### ISSUE TITLE
Reconcile ELB attached machines when a Machine is being deleted

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#1705]
**Describe the solution you'd like**
The `AWSMachine` controller [already watches](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L185-L188) for notifications coming from Cluster API `Machine` objects.

This provider has an ELB that is reconciled [during normal operations](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awsmachine_controller.go#L460-L462), although the `reconcileLBAttachment` never removes a Machine from the load balancer, instead it only ever register new ones to it as shown here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/32eefe16ddea72d4727e0db4ec38e68902bd99bc/controllers/awsmachine_controller.go#L561-L573

We could call `reconcileLBAttachment` during both `reconcileNormal` and `reconcileDelete`. It should have a check that if either `AWSMachine` has a `DeletionTimestamp`, we should deregister the instance from the ELB.

/priority important-soon
/kind feature

**Comment by fabriziopandini** [comment]
/assign

@vincepri @detiber it seems that in order to get this fixed a new IAM permission is required

controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile LB attachment: AccessDenied: User: arn:aws:iam::xxxx:user/bootstrapper.cluster-api-provider-aws.sigs.k8s.io is not authorized to perform: elasticloadbalancing:DeregisterInstancesFromLoadBalancer on resource: arn:aws:elasticloadbalancing:us-west-xxxx:loadbalancer/test-apiserver\n\tstatus code: 403, request id: e31c92ce-1bad-4461-aaf0-e4e83e03ece3\ncould not deregister control plane instance \"i-0796396af2ae985c1\" from load balancer\nsigs.k8s.io/cluster-api-provider-aws/controllers.

any suggestion to get this sorted out?

**Comment by fabriziopandini** [comment]
Ohh... it seems this is already there
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/04921198635ba0881299da26dd28789cd36bc080/pkg/cloud/services/cloudformation/bootstrap.go#L336
Might be my cloud formation is old. re-creating

**Comment by fabriziopandini** [comment]
The grant is there but the bind to resources not 😞
