### ISSUE TITLE
Is `clusterawsadm bootstrap iam create-cloudformation-stack` necessary? 

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-sigs/cluster-api-provider-aws#2075]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I am checking cluster API book, seems there's an extra step to bootstrap IAM. 

```
clusterawsadm bootstrap iam create-cloudformation-stack
export AWS_B64ENCODED_CREDENTIALS=$(clusterawsadm bootstrap credentials encode-as-profile)

```

Could cloudctl use AWS envs directly? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
@Jeffwan I would love to find an alternative to this. The issue right now is that Cluster API initially runs in a Kind cluster, so there's no environment variables present at that time.

However, once the initial cluster is up and we move the controllers to the new cluster, I would definitely like a workflow where we delete the credentials and rely on implicit credentials (EC2 IMDS / IRSA / Kiam).

**Comment by TBBle** [comment]
If I'm following correctly, #2053 should deliever the ability to have the management cluster components running under IRSA instead of node IAM roles.

Then the kind-based bootstrap process would need to create the necessary roles with appropriate trust relationships and deploy the real management cluster in IRSA mode with appropriately-annotated service accounts (per #2053).

This would be very useful for my use-case, as we try to avoid IAM users if possible: all our human users are using `AssumeRoleWithSAML` from our corporate SSO stack, and our existing (non-CAPI) EKS clusters are all using IRSA exclusively (using eksctl to manage the roles and service accounts), rather than relying on EC2 instance roles. The long-term plan is to deny pods access to the instance roles entirely, reserving them for kubelet's requirements.

**Comment by randomvariable** [comment]
@TBBle it's only part of the story. there's also the use case of running Cluster API from your laptop to kick off the creation of the 1st management cluster.

**Comment by TBBle** [comment]
I thought that's what the kind bootstrap cluster was for? Just enough k8s to run as a CAPI management cluster, to then create an (in this case) EKS cluster and make it the management cluster for itself and future worker clusters? Or perhaps I've misunderstood. I can't see any such flow in the docs, making the first non-kind management cluster also be its own manager. Perhaps that happens underneath one of the tools, and I'm just overlooking it in the docs.

That initial kind cluster would need enough AWS credentials to create the IAM Role for #2053 to consume, and once the new management cluster is live with IRSA, no more user credentials are needed, the service accounts via IRSA provide all the permissions.

I guess the specific request for this ticket is that `clusterctl init --infrastructure aws` consumes the `AWS_*` env-vars, more like the Azure provider does, without the extra calls to `clusterawsadm`.

**Comment by dhess** [comment]
So what happened with this issue, in the end? Is it the case that, post-bootstrap, the production management cluster will need the IAM user and credentials used in the `clusterawsadm bootstrap iam create-cloudformation-stack` step in order to perform its operations? Or does #2100 mean that the IAM user can be deleted post-bootstrap?

**Comment by randomvariable** [comment]
We don't create the IAM user by default anymore and haven't done for a long time.

`clusterawsadm bootstrap credentials encode-as-profile` takes your existing credentials and encodes them, following the same logic as the AWS CLI. Because these creds need to land inside a container without access to your home directory or env vars, they need to be temporarily present. If you're running on an EC2 instance with a suitable instance profile, `AWS_B64ENCODED_CREDENTIALS` can be blank and CAPA will resolve using EC2 instance metadata on its own.

Finally, if you're making the created cluster self-managing using `clusterctl move`, then `clusterawsadm controller zero-credentials` will wipe out the secret on the pivoted cluster causing CAPA to fallback to EC2 instance metadata _or_ EKS pod identity depending on what you're using.

**Comment by dhess** [comment]
Thanks for the clarification! I was in fact able to `clusterctl init` using credentials I'd generated via AWS SSO, which is perfect for our case.
