### ISSUE TITLE
When using unmanaged VPCs and upgrading from <v0.5.5 to v0.6.1, CNI security group rules are deleted

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2084]
/kind bug
/priority critical-urgent

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Start with an AWSCluster with unmanaged VPCs running prior to v0.5.5. The spec has no network.cni fields.
Then upgrade to CAPA v0.6.1, the security group rules relating to CNI get deleted.

**What did you expect to happen:**
No change to security groups

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Discussion in Slack suggested enabling defaulting in the controller, with a TODO to remove for v1alpha4.

**Environment:**

- Cluster-api-provider-aws version: v0.6.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Starting from v0.5.5, CNI-related security groups are added to spec by defaulting and ReconcileSecurityGroups() uses the defaulted networkSpec.cni to add CNI-related security groups. Controllers < v0.5.5, they were added by the ReconcileSecurityGroups().

When controllers are upgraded from a version <0.5.4, if AWSClusters do not get defaulted then the security groups were being deleted.

This issue is only observed in the AWSClusters with unmanaged VPC.
Reason is in v0.5.5, "Name" subnet tag was changed and hence the clusters with managed VPC was being defaulted before updating that subnet tag. 
AWSClusters with unmanaged VPC was never hitting defaulting hence CNI related security groups were being deleted.

Added defaulting to the controller solved this issue.

cc @randomvariable
