### ISSUE TITLE
[v1alpha4] Naming and typo changes

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2157]
There are several fixes/improvements we want to do in v1alpha4.

Some of them are in this PR's comments: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121#

This issue is to track naming and typo changes. We can add the changes we think of under this issue.

cc @MarcusNoble

**Comment by MarcusNoble** [comment]
(Copied over from the comments on #2121)

* Rename `NetworkSpec` as just `Network` (Issue #2119)
* Refactor AMI image lookup, either as it's own type so implmentation is consistent or as something else. (Related #2056)
* Should `NonRootVolumes` be renamed. Possibly `SecondaryVolumes` or `AdditionalVolumes`?
* Fix case on `VpcReadyCondition` etc. - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121#discussion_r539968235
* Fix case on `Ebs` - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121#discussion_r539998391
* Fix comment to refer to `DeviceName` instead of `VirtualName` - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121#discussion_r539998634
* Should LaunchTemplate have a property for non-root volumes? - https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2121#discussion_r539999214
