### ISSUE TITLE
Containers still run as root due to non-numeric user in Docker image

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-aws#2222]
/kind bug

**What steps did you take and what happened:**
This is a duplicate of [capi non root user bug](https://github.com/kubernetes-sigs/cluster-api/issues/4046)

**What did you expect to happen:**
capa should not fail when psp for non root users is enabled

**Anything else you would like to add:**
[capi fix](https://github.com/kubernetes-sigs/cluster-api/pull/4064)

**Environment:**

- cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
FYI https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1089#issuecomment-765721150

**Comment by randomvariable** [comment]
@enxebre @JoelSpeed I know OpenShift has some practice around this. Any recommendations?

**Comment by JoelSpeed** [comment]
I had to double check this, but, OpenShift uses an admission plugin to ensure that all pods that don't explicitly get granted a higher security policy, get a runAsUser injected into them at pod creation time. So for our machine controllers for example this gets injected into the pod spec so that each container has

```
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000440000
```

Unfortunately I think this is rather different to how it is being fixed elsewhere in CAPI. When I've had this issue before I've historically set the user and group in the Dockerfile to 65534 IIRC, I noticed that in the [linked fix](https://github.com/kubernetes-sigs/cluster-api/pull/4064), they set it 65532, so perhaps that's a particular value for the distroless image that works here?

No matter what you set in the Dockerfile though, it can be overriden as part of the podspec, so I would think of the Dockerfile as more of a default than an enforced value, mimicking the fix for CAPI seems reasonable here to me
