### ISSUE TITLE
List AWS resources created by CAPA

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2381]
/kind feature
/help

**Describe the solution you'd like**
Create a `clusterawsadm` command that will list all the AWS resources that have been created by CAPA. We can use the tags that are attached to the resources.

**Environment:**

- Cluster-api-provider-aws version: 0.6.5

**Comment by shivi28** [comment]
Hey @richardcase, Almost all the resources created by CAPA have `sigs.k8s.io/cluster-api-provider-aws/cluster/test-cluster-1` tag **except Volumes**. So how **I will list the volumes created by CAPA ?** (because they have no tag).

Second, I need some suggestions on the way command output should look. I have explored resourcetaggingAPI `GetResource()` function,  it's returning the ARN's for all the resources. IMO, I have 2 ways to return the list
1. Just return the ARN list (the user experience is not good)
2. Second return in this way
```
Service             ResourceId        ARN
Ec2 			elasticIP-ID        arn1
Ec2 			elasticIP-ID        arn2
Ec2 			elasticIP-ID        arn3
Ec2 			Instance-ID        arn1
Ec2 			Instance-ID        arn2
Ec2 			Instance-ID        arn3
```
but in this case, I need to parse the ARN string. Is it advisable?
Please suggest if there is any better way to do this

**Comment by richardcase** [comment]
Thanks for working on this @shivi28 :+1: 

For volumes, we should be adding tags. So I think you should treat volumes in the same way as other resources and list the ones that have the tag. At the moment it won't list them as they don't have the tag, but we can make a separate change to ensure that they are tagged correctly. After that, they will be picked up. (I also need to review this change which is related https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2463).

With the output I like 2 as it's a bit more user-friendly. You could use the `github.com/aws/aws-sdk-go/aws/arn` package (or something similar) to parse the ARN. I think we should also support the `--output` flag so that the user can choose to have the output in a table (the default), yaml or json.  We have this `--output` in a few commands for example: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/cmd/clusterawsadm/cmd/eks/addons/list_installed.go#L48

**Comment by shivi28** [comment]
Thanks @richardcase,  will check `github.com/aws/aws-sdk-go/aws/arn` package and go ahead with 2nd approach. I will add all the three output forms: table, yaml and json.
