### ISSUE TITLE
clusterawsadm delete-cloudformation-stack should not return error on successful deletion

### ISSUE THREAD

**Issue by DanielCalvo** [kubernetes-sigs/cluster-api-provider-aws#2392]
/kind feature

When running `clusterawsadm bootstrap iam create-cloudformation-stack` clusterawsadm seems to use sensible defaults to create this cloud formation stack and succeeds:

```
 clusterawsadm bootstrap iam create-cloudformation-stack
Attempting to create AWS CloudFormation stack cluster-api-provider-aws-sigs-k8s-io


Following resources are in the stack: 

Resource                  |Type                                                                                |Status
AWS::IAM::InstanceProfile |control-plane.cluster-api-provider-aws.sigs.k8s.io                                  |CREATE_COMPLETE
(truncated)
```

However, the same sensible defaults do not delete the stack:
```
clusterawsadm bootstrap iam delete-cloudformation-stack
Error: no AWS region configured. Use --region or set AWS_REGION or DEFAULT_AWS_REGION environment variable
```

Passing the `--region` argument allows this command to succeed (it does delete the stack) but it also shows an error message:

```
clusterawsadm bootstrap iam delete-cloudformation-stack --region eu-west-1
Attempting to delete AWS CloudFormation stack cluster-api-provider-aws-sigs-k8s-io
Error: unable to describe stack resources: ValidationError: Stack with id cluster-api-provider-aws-sigs-k8s-io does not exist
	status code: 400, request id: 3f3cf351-480b-405c-b3d8-17ac183fb7fb

```

**Describe the solution you'd like**
clusterawsadmin should be able to create and delete the cloudformation stack using the same arguments consistently, and not show an error message after the stack is deleted.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 

```
clusterawsadm version: &version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.5", GitCommit:"c7c8ae1ee071afbb33c3b45b0f9adbea149581ce", GitTreeState:"clean", BuildDate:"2021-04-15T16:55:53Z", GoVersion:"go1.13.15", AwsSdkVersion:"v1.36.26", Compiler:"gc", Platform:"linux/amd64"}


clusterctl version: clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.16", GitCommit:"6d7649fc5f407ac48b6d8e3929c97822527c0454", GitTreeState:"clean", BuildDate:"2021-04-16T01:01:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

aws --version: aws-cli/2.1.19
```

- Kubernetes version: (use `kubectl version`): v1.20.2
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by Szymongib** [comment]
Hey @sedefsavas, I could take it if that is ok.
From what I see the `--region` flag is ignored all together when running `clusterawsadm bootstrap iam create-cloudformation-stack --region test` and it uses default AWS credentials or env var.

I think it would be the best that both commands use parameters in the same way so we could either delete `--region` flag from both commands and fallback to default credentials, or require it (flag or env var) in both. What do you think?

**Comment by sedefsavas** [comment]
@Szymongib Welcome to the community!

Both create and delete operations either resolve region from env vars or read it from the flag, using the same function: `resolveTemplateRegion`. So that behaviour is the same, cannot replicate the issue described.

But there is an issue in the delete operation, at the end we try to get the deleted resources that is why it shows error, even if CloudFormation is successfully deleted. We need to address that by waiting until delete stack is successful, by doing something like this:
`cfn.New(sess).WaitUntilStackDeleteComplete()`
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/ab3afdef21ab208a780810034f615fe0b48a6c1a/cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go#L159

/assign @Szymongib

**Comment by Szymongib** [comment]
Thanks @sedefsavas!
Could you share the version you used when trying to reproduce? I managed to reproduce the issue from main branch as well as 0.6.5, with the following:
```
unset AWS_REGION
clusterawsadm iam delete-cloudformation-stack
```
This results in:
```
Error: no AWS region configured. Use --region or set AWS_REGION or DEFAULT_AWS_REGION environment variable
```
as an issue describes.

The `create-cloudformation-stack` actually works because it uses configuration from `~/.aws/credentials` if env is not set (this comes by default from AWS client lib).
Furthermore running:
```
clusterawsadm bootstrap iam create-cloudformation-stack --region it-does-not-exist
```
actually works as `createCloudFormationStackCmd` does not seem to call `resolveTemplateRegion` and again `~/.aws/credentials` is used.

Regarding the issue with error message after deletion, I think we can just remove call to `ShowStackResources` as waiting for deletion is already part of `cnfSvc.DeleteStack(...)` https://github.com/kubernetes-sigs/cluster-api-provider-aws/blame/main/cmd/clusterawsadm/cloudformation/service/service.go#L128.

I might be still missing something, but I have created the PR #2423 so we can continue discussion there.

**Comment by sedefsavas** [comment]
@Szymongib
Good points! 
In the PR, I proposed a solution to resolve region from flag, env var, and config in this order.
