### ISSUE TITLE
Update calico in e2e tests

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2435]
We use calico v3.13.2 for our e2e tests: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a183f580873ed46aebdbba77da212a3476682aa/test/e2e/data/cni/calico.yaml#L2

We should upgrade this to a more recent version such as 3.18.4, for reasons like `apiextensions.k8s.io/v1beta` is deprecated.

/help
/good-first-issue
/milestone v0.7.x
/priority backlog

**Comment by Evalle** [comment]
hi @sedefsavas, a couple of questions:
1. should we also change `apiextensions.k8s.io/v1beta` to `apiextensions.k8s.io/v1` as in https://docs.projectcalico.org/manifests/calico.yaml? 
2. The latest calico image is `v3.19.1` (see https://docs.projectcalico.org/manifests/calico.yaml), should we use it instead of `3.18.4` ? 
3. What about `calico_eks.yaml`? https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a183f580873ed46aebdbba77da212a3476682aa/test/e2e/data/cni/calico_eks.yaml#L35

Thanks!

**Comment by sedefsavas** [comment]
> 1. should we also change `apiextensions.k8s.io/v1beta` to `apiextensions.k8s.io/v1` as in 
https://docs.projectcalico.org/manifests/calico.yaml?
> 
Yes, we can use this yaml completely and add the version as comment at the too. If there are other changes we do, maybe add them as note too.
> 2. The latest calico image is `v3.19.1` (see https://docs.projectcalico.org/manifests/calico.yaml), should we use it instead of `3.18.4` ?
> 
Yes 
> 3. What about `calico_eks.yaml`? https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a183f580873ed46aebdbba77da212a3476682aa/test/e2e/data/cni/calico_eks.yaml#L35
> 
I don't know the specific changes in there, if you can identify and do the same changes in the new version too, go ahead. Otherwise, we can track it on another issue.
