### ISSUE TITLE
Private EKS cluster SG forbids by default API access from outside of cluster

### ISSUE THREAD

**Issue by martin-ducar-gd** [kubernetes-sigs/cluster-api-provider-aws#2465]
/kind bug

**What steps did you take and what happened:**
If you create EKS cluster with:
```yaml
  endpointAccess:
    public: false
    private: true
```
Than default security group setup is done in this way:
* Controll plane primary SG:
  * Ingress
    * All Traffic from self (reference to same SG id)
  * Egress
    * All Traffic to 0.0.0.0/0 
* Controll plane secondary SG:
  * Ingress
    * Port 22 TCP from SG of bastion 
* Nodegroup:
  * uses same  SG as Controll plane primary SG

**What did you expect to happen:**
This works for public cluster to an extent but is still weird setup. If you have private cluster it basically means noone except cluster itself can talk to API. Coupled with another bug which is `networkSpec: {  securityGroupOverrides: }` is not working for EKS which will be raised as different bug makes really private cluster completely unusable.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 
```sh
$ kubectl get deploy -n capa-system capa-controller-manager -o yaml | grep cluster-api-aws-controller
        image: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller:v0.6.6
```
- Kubernetes version: (use `kubectl version`): 
```sh
$ kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:39569
KubeDNS is running at https://127.0.0.1:39569/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
- OS (e.g. from `/etc/os-release`): 
```sh
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by richardcase** [comment]
After chatting with @paulcarlton-ww 

/assign @paulcarlton-ww 

Ping me if you need a hand with anything

**Comment by paulcarlton-ww** [comment]
I will look at this issue

**Comment by paulcarlton-ww** [comment]
@martin-ducar-gd I've been investigating this and recreated issue.  When I add a bastion node I can access the api server but I need to add a security group rule to the control plane secondary SG to open port 443 to do so. Will investigate how to specify this in CAPA cluster definition.

**Comment by paulcarlton-ww** [comment]
I'm not seeing a way to automatically add the ingress rule above to allow access to api from the bastion host or elsewhere. 

I tried adding
```yaml
  networkSpec:
    cni:
      cniIngressRules:
      - description: "api access"
        fromPort: 443
        toPort: 443
        protocol: "tcp"
```
But it didn't get that far, management node controller failed to access tenant cluster api.

My thinking is a mechanism to add rules to a security group created for the cluster is required?
But seems to me the management node controllers need to be able to access the tenant's private API which is only possible via a proxy (like the bastion host) that is inside the tenant vpc because a private api means a 10. address that is not useable from outside the vpc

**Comment by paulcarlton-ww** [comment]
So issue is that setting 

```yaml
 endpointAccess:
    public: false
    private: true
```

means you get exactly what you asked for, an API server that is only accessible from within the vpc.

The default security group setup does not allow access from the bastion host, we should add an option to `endpointAccess` to allow the user to specify that the bastion host's SG should be allowed API access, not just SSH. 

The management cluster where the CAPI/CAPA controllers are running needs access to the api server of the cluster it is provisioning. If this is in the same vpc we just need a way to specify the management clusters SG so it can be granted access to the tenants API.

If the management cluster is in a different vpc then the user would also need to configure vpc peering so that the management server can access the private api of the tenant.

If the management server is not running in AWS then theoretically a user could setup a proxy on the bastion host that could forward API server requests, although this would need an enhancement to generate a kubeconfig with the bastions address in, but that is out of scope for the current issue.

So the proposed fix for this issue is to add two new fields to `endpointAccess` that apply when the private is true and public is false...

```yaml
 endpointAccess:
    public: false
    private: true
    bastionAccess: true
    securityGroupsAccess:
    - id: <id of SG to be granted access to private api>
    - ...
```

**Comment by richardcase** [comment]
@paulcarlton-ww - could we change the name of `securityGroupsAccess` so that its obvious that this is additional security groups?

**Comment by richardcase** [comment]
Also, we should create another issue for the docs to be updated to give guidance on VPC peering when used with CAPA.

**Comment by paulcarlton-ww** [comment]
So the proposed fix for this issue is to add two new fields to endpointAccess that apply when the private is true and public is false...

 endpointAccess:
    public: false
    private: true
    bastionAccess: true
    additionalSecurityGroupsAccess:
    - id: <id of SG to be granted access to private api>
    - ...

**Comment by paulcarlton-ww** [comment]
I've created a vpc peer from management cluster's vpc to the tenants vpc and routes from each subnet's private router to the tenant vpc cidr and now the tenant cluster's private API endpoint is accessible from mgmt cluster, no need for security group change! Possibly because the default security group in the tenant vpc allows all traffic within group and the peering makes the connection from the mgmt vpc look local?

**Comment by paulcarlton-ww** [comment]
I think we still should add `bastionAccess` field but not needed to fix this specific issue I think

**Comment by paulcarlton-ww** [comment]
Actually something is still not right, control plane controller gets 

```
E0609 10:48:43.227387       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile aws-iam-authenticator config for AWSManagedControlPlane tenant01/tenant01-control-plane: getting client for remote cluster: Get https://F6352D22CDA6B643C65FDE4D182552AC.yl4.eu-west-1.eks.amazonaws.com/api?timeout=1m0s: dial tcp 10.1.139.235:443: i/o timeout" "controller"="awsmanagedcontrolplane" "name"="tenant01-control-plane" "namespace"="tenant01"
```

From my ubuntu pod in mgmt cluster I can access the tenant api but get a forbidden response, although I can list api-resources.
I tried adding the mgmt cluster security group to the tenant cluster's controlplane security group but as expected that didn't change anything.

From bastion I can access api correctly, with security rule to allow access to api.

**Comment by martin-ducar-gd** [comment]
@paulcarlton-ww sorry for delay. that `securityGroupsAccess` filed in `endpointAccess` seems like reasonable first fix sure.

**Comment by martin-ducar-gd** [comment]
But another more conceptual issue is we are using strange SG setup. If you look at EC2 clusters from CAPA they split SGs for Controll plane and for Nodes hopefully that is also something we can agree EKS would benefit from instead of using only one for both. than the securityGroupsAccess will be for Controll plane SG and the Nodes SG will also allowed in controll plane SG.

**Comment by martin-ducar-gd** [comment]
that setup will actually than unify the setup a bit between EKS and EC2 clusters and than Security group override logic can be reused largely of course `apiserver-lb`, and `lb` field is arbitrary for EKS most probably but otherwise same.

**Comment by richardcase** [comment]
@paulcarlton-ww - for consistency with naming elsewhere could it be named `AdditionalSecurityGroups`

**Comment by paulcarlton-ww** [comment]
ah seems kubectl executed from within a pod defaults to the host cluster api! Adding --kubeconfig ... makes it use the kubeconfig of the tenant cluster!

Now it is failing to connect, despite SG rules, vpc peering and routes being setup, investigating

**Comment by paulcarlton-ww** [comment]
Figured out networking and security groups now, see #2484 
Working on fix to this issue

**Comment by randomvariable** [comment]
cc @sedefsavas

**Comment by defyjoy** [comment]
This item has been open for quite a while and I had to add the ingress rules from - 
- Management cluster SG => Workload Cluster SG's ingress rule ( All Traffic ) 
- Had to add the VPC Cidr => Workload cluster's SG's ingress rule for HTTP/s endpoint access . 

Do we have any solution either we can add our own SG OR we can add our ingress rules to the SG's created by CAPI ?
