### ISSUE TITLE
Add AWSClusterTemplate type

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api-provider-aws#2575]
/kind feature

**Describe the solution you'd like:**
Add a new CRD named AWSClusterTemplate. This is needed for ClusterClass.
In the short term this type will not be used outside of ClusterClass.

**Comment by fabriziopandini** [comment]
FYI When implementing this please make sure that the template type applies the same defaulting & validation rules of the actual type, otherwise this could trigger continuous reconcile loop down the path when comparing the desired state (the AWSClusterTemplate object) with the actual state (the instance of AWSCluster generated from the template)

**Comment by ykakarap** [comment]
@Ankitasw 
I am sorry I didnt realize you already had this issue assigned to you. I just opened a PR for this while I was working on similar PRs for other providers. Sorry for that.

Since you are already interested in this can you please review the PR :)

**Comment by ykakarap** [comment]
PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2585

**Comment by Ankitasw** [comment]
@ykakarap oh, that's ok if you have raised a PR, I was about to raise a PR today, anyways just for future, please check the assignee in the issue before raising the PR, other people in community also want to work on ClusterClass 😅

**Comment by ykakarap** [comment]
You are completely correct. 
I thought I assigned the issue when I created it. 
I should have double checked. My bad. 😅

**Comment by ykakarap** [comment]
/assign

Assigning not to avoid future confusion. 

/lifecycle active
