### ISSUE TITLE
Ordering of subnets is inconsistent, causing problems with tools expecting consistency in ordering

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2797]
/kind bug
/area networking
/priority important-soon
/milestone v0.8.0

**What steps did you take and what happened:**

Reported by @voor :

Cluster API AWS sometimes needs to be populated with the subnet ID's for unmanaged VPCs if the subnets is larger in the VPC than the subnets you wish to restrict Kubernetes nodes to.  For example, if you have 6 subnets but only want to put nodes into 4 of them, you would explicitly pass the ID of subnets into the AWSCluster object at cluster creation.

The CAPA controller meanwhile reconciles this list by using tags to lookup the subnets.  The AWS API does not guarantee the ordering of that returned list, and so CAPA controller can rarely mutate the ordering.

So the array of:

```yaml
- 1
- 2
- 3
```

becomes:

```yaml
- 3
- 2
- 1
```

Meanwhile, kapp-controller, which is reconciling against this with what was stored in the source of truth, understands the array to have an ordering of 1, 2, 3.  This results in odd behavior that will in extremely rare circumstances give you a jumbled array of:

```yaml
- 1
- 2
- 1
```
 
his will cause new Machines to be unable to find appropriate subnets, and result in an error that reads like this:

`no subnets available in availability zone "us-west-1b"`

**What did you expect to happen:**
Subnet list is consistent, if I create a cluster with an array of subnets I would expect that ordering to remain the same, or be in a predictable and documented order so that I can make sure kapp-controller and CAPA agree.  (Even if that requires me to sort the subnets alphabetically beforehand)

 

Alternatively, subnet list becomes immutable after cluster creation. (As I am writing this I'm wondering if there's a way for kapp controller to ignore this field after initial deploy)

**Anything else you would like to add:**

(Commentary by me)

The ultimate root cause of this is that AWS does not guarantee the order of the subnets it returns as it is wholly backed by DynamoDB which does not guarantee the order of rows returned in a query. We should ideally preserve order of input when comparing slices, and at worst have a preferred sort order.

**Environment:**

- Cluster-api-provider-aws version: v0.7.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@voor We tried to reproduce it locally with the tests, even changed the order of subnets in output of AWS APIs but couldn't get the above mentioned results. 
We would need more examples of the resources which shows this behavior to understand the issue more. At-least what we understand from the code, the ordering is not altered. You can probably omit the sensitive details from the resources and give the other details here which shows the subnet ordering is affected.
/priority awaiting-more-evidence

**Comment by voor** [comment]
This is definitely still occurring with extreme irregularity, but we were able to change our kapp config to handle the changes.  Rather than iterate through each index, kapp just ignores the entirety of the subnet block.

Since we fixed the issue elsewhere, and it happens with such an extremely small chance, I highly doubt I'll be able to recreate it.

Instead of:
```
- [spec, networkSpec, subnets, {allIndexes: true}, id]
- # Repeat for each subnet field
```
We now just have:
```
- [spec, networkSpec, subnets]
```

So if the ordering of the subnets changes, kapp-controller will not complain.

**Comment by voor** [comment]
Suggest we change this issue to be some kind of warning or documentation that this occurs with extreme infrequency, and to plan accordingly.  Since this is consistently inconsistent with all AWS queries based on tags, it might be worth noting in a more common place.  I would say this is a misalignment with Kubernetes philosophy and justifies a call-out.
