### ISSUE TITLE
Add documentation for use of failure domains in CAPA with single-AZ constraints

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2924]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

In discussions around whether or not MDs should support multiple AZs, I believe we've reached the conclusion that this is not a thing we want to support as it hides failure domains from consumers such as Cluster Autoscaler. We should make clear in documentation and APIs where this constraint is valid. Relates to #2298 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
I found one such reference but we have already mentioned about using only one AZ [here](https://cluster-api-aws.sigs.k8s.io/topics/consuming-existing-aws-infrastructure.html#placing-ec2-instances-in-specific-azs)

**Comment by sedefsavas** [comment]
> @sedefsavas I found one such reference but we have already mentioned about using only one AZ [here](https://cluster-api-aws.sigs.k8s.io/topics/consuming-existing-aws-infrastructure.html#placing-ec2-instances-in-specific-azs)

@Ankitasw 
We should document this in a more generic place, because this constraint does not only exist when you use externally managed network resources.

I think we should consider having a failure domains support documentation similar to CAPZ: https://capz.sigs.k8s.io/topics/failure-domains.html?highlight=%23%23%20Failure%20domains%20in%20Azure#failure-domains-in-azure

This new document should cover both workers and control plane and we already have docs for [Multi-az control plane 
](https://cluster-api-aws.sigs.k8s.io/topics/multi-az-control-planes.html)

Also, considering this is a MD related constraint, this should be clear in cluster api book. If there is not clear warning there, it'd be good to open an issue.

**Comment by Ankitasw** [comment]
@sedefsavas do we want to change the scope of this issue to add failure domains doc such that we can specify above constraint in failure domain doc?

**Comment by sedefsavas** [comment]
> @sedefsavas do we want to change the scope of this issue to add failure domains doc such that we can specify above constraint in failure domain doc?

Yes, feel free to change the title.

**Comment by Ankitasw** [comment]
CAPI issue: https://github.com/kubernetes-sigs/cluster-api/issues/5542

**Comment by Ankitasw** [comment]
/retitle Add documentation for use of failure domains in CAPA with multi-AZ constraints

**Comment by Ankitasw** [comment]
/retitle Add documentation for use of failure domains in CAPA with single-AZ constraints
