### ISSUE TITLE
Migrate to updated go-logr interface

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#2944]
go-logr changed the Logger interface to a struct and introduced a LogSink interface which is slightly different.

I've opted for embedding the old interface, because I think otherwise we would have to refactor a lot of code.

Not sure if that's okay / there are better alternatives

_Originally posted by @sbueringer in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2943#r747734949_

**Comment by bisakhmondal** [comment]
Just took a good look there. I am having certain doubts.
What do we want to achieve here - remove the `cloud.Logger` interface that we had to add extra?
It would be really trickier because of this extra `Init` method inside the `LogSink` interface ( [ref](https://github.com/go-logr/logr/blob/28755ae811e8511239e62a7b90b5ca808b691fca/logr.go#L419) ).

```go
         if params.Logger == nil {
		log := klogr.New()
		params.Logger = &log
	}
```

the klogr actually returns a logr.Logger (https://github.com/kubernetes/klog/blob/4ce6ac629780f9f806fd85af47a1862683f16db6/klogr/klogr.go#L41-L59) object that is compatible with current go-logr implementation but I am not sure what do we want to migrate.

Thank you : )

**Comment by sedefsavas** [comment]
@bisakhmondal we are considering a refactoring for logging in this issue
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3152

It'll be good to consider this under that effort as well as we are trying to be consistent in the capi ecosystem.
Feel free to add your findings about what CAPI and other providers are doing in regards to this to the other issue.

**Comment by zeborg** [comment]
For additional reference, the need for this change was introduced due to an upgrade from `go-logr` v0.4.0 to the latest one. I believe that finding differences in the `logr.Logger` implementation within the package before and after this change might be helpful.
