### ISSUE TITLE
Exclude aws credentials when pivoting cluster

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#297]
/kind feature
/priority important-soon

Depends on: https://github.com/kubernetes-sigs/cluster-api/issues/556

Currently w hen clusterctl pivots the cluster-api components, the aws credentials secret which is used for the bootstrapping cluster is also pivoted to the target cluster. Since the target cluster requires an existing IAM profile that provides all of the required permissions for the cluster and machine actuators, we should default to using the instance profile for credentials instead of the user provided credentials (which may be time limited).

**Comment by roberthbailey** [comment]
As I mentioned in the meeting today, we have three categories of "things" that clusterctl should know about:

1. Things that should exist only in the bootstrap cluster
1. Things that should exist in both the bootstrap and target clusters
1. Things that should exist only in the target cluster

Right now clusterctl assumes that everything falls into the second bucket, except for the things specified via the addon flag, which I added so that we could put things into the third bucket. This feature request is about separating things that should be in the first bucket, which was generally agreed was a good idea.

The open question is about how to specify the differences. We can do it via flags, component config entries, different files, or annotations. Or maybe something else I haven't thought of. 

Ideas welcome!
