### ISSUE TITLE
V1.1.0 is not compatible with v1.0.0 release due to setting up an optional field in the controller

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3003]
In our community meetings, we have decided to only do minor releases starting from v1 and do a major release for breaking changes. So, all v1.x releases need to be compatible with each other.

In v1.1.0, we introduced a bug by adding an optional field

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3e61428d885f2eaeab1a7dffc4d17270a20c6675/api/v1beta1/awscluster_types.go#L156

and then setting it a value in the controller:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3e61428d885f2eaeab1a7dffc4d17270a20c6675/pkg/cloud/services/elb/loadbalancer.go#L72

Now, external controllers that use CAPA API v1.0.0, is failing to update AWSCluster because admission webhook denies the request with `invalid: spec.controlPlaneLoadBalancer.name: Invalid value: "null": field is immutable` error

/kind bug
/priority critical-urgent
/milestone v1.2.0
/triage accepted

**Comment by sedefsavas** [comment]
@dilyevsky What would not be working if we remove the LB name assignment in BYO LB?

**Comment by dlipovetsky** [comment]
The external controller doesn't know about the Name field, and the defaulting webhook is setting it to nil, but the Name field has already been set by the v1.1.0 CAPA controller, so that's causing the validating webhook to reject the update as a change? 

@sedefsavas and I talked about possible workarounds.

The first option I'll try is to generate the default ELB name in the code, and to _not_ persist it in the AWSCluster Spec. The reasoning is: Any client that is not aware of the Name field would get the default value, and if the default value is not persisted, then that client can update the AWSCluster without hitting the validation error. Any client that _is_ aware of the Name field can use it. And although the default value won't be persisted to the Spec, it _will_ still be in the Status, and so it will be discoverable.
