### ISSUE TITLE
Use AMI lookup for bastion hosts instead of using hardcoded values

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#3108]
We are using Ubuntu images published on AWS community AMIs for bastion host if an image id is not provided.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/50af6ec5ce7a183b67d23a187e687c42fef24176/pkg/cloud/services/ec2/ami.go#L191-L195

Currently, default AMIs used for bastion are hardcoded. To use the latest published images to avoid any security issues, we can do a lookup and automatically use the latest images published by Ubuntu.

**Comment by sedefsavas** [comment]
We already install updates with a cron job in the bastion host: 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/ab3afdef21ab208a780810034f615fe0b48a6c1a/pkg/cloud/services/userdata/bastion.go#L23

So this is not critical in terms of security.

**Comment by Ankitasw** [comment]
@sedefsavas Since bastion is in `ClusterScope`, is there a way to get the kubernetes version used in the bastion, as it will be required to perform default AMI lookup?
As of now we can get kubernetes version only in `MachineScope`. To solve above issue, shall we introduce new field `kubernetesVersion` into the `Bastion`?
