### ISSUE TITLE
Add verify-book-links to Makefile target

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3176]
There are a few Makefile targets that are used in other cluster api projects that will be great to add to CAPA. 

One of them is `verify-book-links` which checks if book links are correct

Refer to [cluster-api](https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L365-L367) for implementation details.

**Comment by zeborg** [comment]
Update:
The implementation here is fairly simple, but I'm running behind due to my system's arch's _(arm64)_ incompatibility with the [image](https://hub.docker.com/_/maven?tab=tags&page=1&name=3-jdk-14) _(amd64)_ provide here:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d4e16e42b26126a95e643091b7647bd525f37c72/hack/tools/plantuml.Dockerfile#L30

@pydctw I'd like to know if it is possible for us to use an upgraded image here which has both `arm64` and `amd64` support. Thanks!

**Comment by pydctw** [comment]
I guess it should be fine if the upgraded image support both. However, I don't have much context on how platuml is used in CAPA.

@sedefsavas, could you comment?

**Comment by sedefsavas** [comment]
> Update: The implementation here is fairly simple, but I'm running behind due to my system's arch's _(arm64)_ incompatibility with the [image](https://hub.docker.com/_/maven?tab=tags&page=1&name=3-jdk-14) _(amd64)_ provide here:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/d4e16e42b26126a95e643091b7647bd525f37c72/hack/tools/plantuml.Dockerfile#L30
> 

@zeborg Yes, this is one of the things we want to achieve as part of https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2930
If you could find such image, feel free to use here.
