### ISSUE TITLE
CAPA webhook should allow more SecondaryCidrBlock ranges

### ISSUE THREAD

**Issue by richardchen331** [kubernetes-sigs/cluster-api-provider-aws#3274]
/kind feature

**Describe the solution you'd like**
Currently the webhook only allows 100.64.0.0/10 or 198.19.0.0/16 CIDR range (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go#L299). However AWS doc shows that CIDRs like 10.0.0.0/8 and 172.16.0.0/12 are also allowed (https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-resize). We should update the webhook to allow these ranges as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Thanks for reporting this.
Looks like there is a change in the supported CIDRs as secondary CIDRs since the time this was implemented.

Existing code is following this:
https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/

After fixing it, we should probably have an e2e test for this. A new test is not needed, could simply append a secondary CIDR to an existing test.

/triage accepted
/priority important-soon
/milestone v1.x

**Comment by Ankitasw** [comment]
@richardcase do we need this restriction at all now? As the CIDR blocks allowed now falls under both RFC1918 and non RFC1918 address.
Reference: https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-eks-adds-support-for-public-ip-addresses-within-cluster-v/
