### ISSUE TITLE
Enable apidiff to report only actual breaking changes 

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-aws#3282]
/kind feature

**What steps did you take and what happened:**
Currently, apidiff reports any change in exposed field or in an exposed function as a breaking change. While apidiff is useful for reviewers to check the api changes which are compatible vs incompatible, the reviewers still have to make an informed decision on whether or not to promote this change. 

**What did you expect to happen:**
apidiff should only inform about real breaking change within the current branch.

**Anything else you would like to add:**
We can consider moving the code used by CAPA to internal(ref issue [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2925)) but not sure if that makes sense here. Any thoughts are welcome here.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
Given that most of CAPA code is designed for internal consumption, we can add a warning to the book stating that which parts of the code is safe to use.

clusterawsadm libraries are probably the only bits that we would want to expose.

Instead of moving everything to internal packages, how about we only document this fact and change apidiff to check only api packages?

Following Cluster API convention complicates the repo structure and if we do not need it, we don't need to follow it.

**Comment by pydctw** [comment]
+1 to change apidiff to check only api packages.

**Comment by sedefsavas** [comment]
cc @meghanajangi
