### ISSUE TITLE
Streamline GINKGO variables usage in Makefile target

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3390]
/kind feature

**Describe the solution you'd like**
Our e2e tests are using a mix of E2E_FOCUS and GINKGO_SKIP that are feeding into GINKGO_ARGS.

```bash
ifdef E2E_FOCUS
	override GINKGO_ARGS += -focus="$(E2E_FOCUS)"
endif
...
ifdef GINKGO_SKIP
	override GINKGO_ARGS += -skip "$(GINKGO_SKIP)"
endif
```

It will be great to define GINKGO_FOCUS (replace E2E_FOCUS) and GINKGO_SKIP as separate variables to be consistent with other providers and make it easier to use them in test-infra.

For example, test-e2e make target can be defined as follow.
```bash
# CURRENT
$(GINKGO) -tags=e2e $(GINKGO_ARGS)...

# DESIRED
$(GINKGO) -tags=e2e -focus="$(GINKGO_FOCUS)" -skip="$(GINKGO_SKIP)" $(GINKGO_ARGS)...
```

**Anything else you would like to add:**
Some jobs need to be modified in https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws with this change.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by photra** [comment]
Hi @pydctw, do you have a preference on where `GINKGO_FOCUS` and `GINKGO_SKIP` should be declared? I am thinking of inserting them at line 65 in the Makefile.

Since they are now variables, I will remove their definitions feeding into `GINKGO_ARGS` and amend `test-e2e` and `test-e2e-eks` with our new usage.

Additionally, I will submit another PR in `kubernetes/test-infra` to modify the jobs to use our updated variables. The following contain previous usage with `E2E-FOCUS` and will be updated: `cluster-api-provider-aws-presubmits.yaml`, `cluster-api-provider-aws-periodics-release-0-7.yaml`, `cluster-api-provider-aws-periodics-clusterclass.yaml`.

`cluster-api-provider-aws-periodics-release-0-6.yaml` still uses `E2E_UNMANAGED_FOCUS`. I can update it to our new usage as well.

Please let me know if you would like any steps above done differently!

**Comment by pydctw** [comment]
Hi @photra, thanks for your interest in the issue.

> do you have a preference on where `GINKGO_FOCUS` and `GINKGO_SKIP` should be declared? I am thinking of inserting them at line 65 in the Makefile.

As [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/Makefile#L140-L173) is where GINKGO or E2E related variables are used, maybe before those lines but no preference. 

The steps you describe sound good to me 👍

**Comment by photra** [comment]
Hi @pydctw, I just submitted a PR to address this issue. I left the deprecated `E2E_UNMANAGED_FOCUS` intact for removal in a later PR when my `test-infra` merges their side's PR. Let me know if you have any feedback!
