### ISSUE TITLE
Stale nodes left behind on a workload cluster

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-aws#3434]
/kind bug

**What steps did you take and what happened:**
- Create a workload cluster with a MHC targeting NotReady worker nodes 
- For some reason, the worker nodes of the cluster do not get into the Ready state (the CPI pods do not get deployed)
- MHC reaps the not Ready Machines to retry creating new nodes.
```bash
[vc-robo@sc2-10-187-103-200 worker]$ k get nodes
NAME STATUS ROLES AGE VERSION
robo-antrea-control-plane-2z4j9 Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-gpwnq Ready control-plane,master 8h v1.20.4
robo-antrea-control-plane-j8kq5 Ready control-plane,master 16h v1.20.4
robo-antrea-md-0-6769cbc7cd-25h2m NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-25xg9 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-445kj NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-49cxp NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-4cc59 Ready <none> 8h v1.20.4
robo-antrea-md-0-6769cbc7cd-4n6wj NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-4p5c4 NotReady <none> 11h v1.20.4
robo-antrea-md-0-6769cbc7cd-4t2hd NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-52gwb NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-54vmq NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-5mj54 NotReady <none> 14h v1.20.4
robo-antrea-md-0-6769cbc7cd-5xw9j NotReady <none> 13h v1.20.4
robo-antrea-md-0-6769cbc7cd-6vh4z NotReady <none> 9h v1.20.4
robo-antrea-md-0-6769cbc7cd-6zvrd NotReady <none> 15h v1.20.4
robo-antrea-md-0-6769cbc7cd-7czsf NotReady <none> 12h v1.20.4
robo-antrea-md-0-6769cbc7cd-7l6xp NotReady <none> 8h v1.20.4
``` 

**What did you expect to happen:**
Reaped nodes by MHC should not show up in the output of `kubectl get nodes`

**Environment:**

- Cluster-api-provider-aws version: v1.1.0
- Kubernetes version: (use `kubectl version`): any version
- OS (e.g. from `/etc/os-release`): n/a

**Comment by Harsh0018511** [comment]
Hi, I would like to work on this issue as part of our College Project. If possible could you please direct me to some resources where I can understand more about this topic and issue.
/assign

**Comment by Skarlso** [comment]
Honestly, this issue is pretty strange.

First, the expected outcome:

```
 Reaped nodes by MHC should not show up in the output of `kubectl` get nodes.
```

Why not? Also, that's probably not something we can influence; it depends on how `kubectl` works.

Maybe the desired outcome was no reaped nodes?

Second, I'm not sure what MHC is. In my context, it's Machine Health Check, but I could be wrong, and OP is using some kind of load balancer type thing. But in that case, I'm still unsure what the problem is because I believe the root cause is the machines not getting into `Ready` state for some reason. This is why they are reaped, which IS a perfectly normal behaviour.

@Harsh0018511 I would suggest you look for a different issue that is more straightforward. :)

**Comment by Harsh0018511** [comment]
@Skarlso Sure. Thanks for the reply.
