### ISSUE TITLE
apidiff target verify silently fails and prints errors in CI

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-aws#3443]
/kind bug

**What steps did you take and what happened:**

CI prints:
```
./hack/verify-boilerplate.sh
fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3442/pull-cluster-api-provider-aws-verify/1518584914981687296#

Also, the command fails and it's not making the job fail.

**What did you expect to happen:**

CI should work nicely without errors and CI to fail when some command execution fails.

**Comment by sedefsavas** [comment]
Does this solve the issue:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3442

**Comment by invidian** [comment]
Do you mean, does #3442 solves this issue? If so, then no, this issue is unrelated.

**Comment by Ankitasw** [comment]
I think we are seeing this error log in multiple places and my guess is wherever `git diff` is used, we are getting this. But the same way we are doing in cluster-api project as well.

**Comment by Callisto13** [comment]
👋 I have a fix for this, can I be assigned?

**Comment by Ankitasw** [comment]
yes sure
/assign @Callisto13

**Comment by Callisto13** [comment]
The error came in with be85bb3. It is not _technically_ anything to do with `apidiff` (or any other make command).

A var is being set in the root `Makefile`: `APIDIFF_OLD_COMMIT ?= $(shell git rev-parse origin/foo)`.

The `shell` is run when the file is loaded, regardless of whether it is being used. If we were to make it fail, it would fail for every `make` which has not got an `origin/main` or set the `APIDIFF_OLD_COMMIT` before the call. I imagine this would not be cool for targets which do not need this var?

I can fix the `git diff` error in the `apidiff` target specifically by removing the `if` which is not needed if we want that to genuinely fail the target on git exit 1. But for any top level env var set with `shell`, we probably don't want to actually make it fail. In this case since `apidiff` is genuinely using that var we can ensure the var is set correctly, which it looks like it is (as seen in the above commit).

The issue then becomes the noise from all the targets which don't use that var, but end up triggering that error simply by being in the same file as the `shell` expansion. We could a) ignore it since it is not an actual failure, or b) redo the original change to get that commit sha to go-apidiff differently.

Worth nothing that there are lots of places where vars are being set globally with the outcome of `shell git ...` so same question for all of them I guess.

**Comment by invidian** [comment]
Thanks @Callisto13 for having a look. Indeed my original report was mainly about things failing without any effect and polluting the CI logs. As the `apidiff` does not run as part of `verify` target, maybe we can just move this variable definition to the target itself? Like:
```diff
$ git diff
diff --git Makefile Makefile
index 1135675a..13709c51 100644
--- Makefile
+++ Makefile
@@ -317,9 +317,8 @@ verify-gen: generate ## Verify generated files
                echo "generated files are out of date, run make generate"; exit 1; \
        fi

-APIDIFF_OLD_COMMIT ?= $(shell git rev-parse origin/main)
-
 .PHONY: apidiff
+apidiff: APIDIFF_OLD_COMMIT ?= $(shell git rev-parse origin/main)
 apidiff: $(GO_APIDIFF) ## Check for API differences
        @if (git --no-pager diff --name-only FETCH_HEAD | grep "api/"); then \
                $(GO_APIDIFF) $(APIDIFF_OLD_COMMIT) --print-compatible; \
```

This way it will at least be evaluated only on this specific target as far as I understand.

**Comment by Callisto13** [comment]
👍 yep that makes sense
