### ISSUE TITLE
No ~/.kube/config when minikube launched via clusterctl

### ISSUE THREAD

**Issue by echarles** [kubernetes-sigs/cluster-api-provider-aws#359]
/kind bug

**What steps did you take and what happened:**

When I launch clusterctl, a minikube instance is created but the ~/.kube is not populated with a config file as usual.

To have the kubectl operationql, I workaround creating a minikube instance; stopping it; and launching the clusterctl after. In that case, the existing minikube instance is used and I can use the kubectl command to query minikube:

**What did you expect to happen:**

launching from a naked env with clustectl should populate the ./kube folder with a config so it can be used with kubectl.

Otherwise, it should indicate where the config resides (didn't find it...).

**Environment:**

- Cluster-api-provider-aws version: Built from source from  e74f4f9 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):  Ubuntu

**Comment by detiber** [comment]
We definitely need to document this better, but the default of not updating the default kubeconfig with minikube is intentional.

You can find the created kubeconfig for minikube in the current working directory when running `clusterctl`, it is named `minikube.kubeconfig`.

Alternatively, if you want to update the default kubeconfig, you can also run `minikube update-context`.

**Comment by echarles** [comment]
Thx @detiber - minikube update-context` did not work for me but `KUBECONFIG=./minikube.kubeconfig` did the job.

I guess this decision has been taken to consider minikube as ephemeral before pivoting to the real cloud cluster ... to be confirmed in #296.

I will open a PR with doc update on this.
