### ISSUE TITLE
Ability to define disk type in AWSManagedMachinePool

### ISSUE THREAD

**Issue by phenixblue** [kubernetes-sigs/cluster-api-provider-aws#3690]
/kind feature

**Describe the solution you'd like**

Would like a filed added to allow for defining the disk type (e.g. gp2, io1, etc...) within the AWSManagedMachinePool spec.

**Anything else you would like to add:**

Today the spec only allows for specifying disk size, but maybe something similar to the [volume type](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f22d6f61d230a5046acc77295de604c9aa29e1ad/api/v1beta1/types.go#L224) in the [AWSMachineSpec](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f22d6f61d230a5046acc77295de604c9aa29e1ad/api/v1beta1/awsmachine_types.go#L124)

**Environment:**

- Cluster-api-provider-aws version: v1.5.0
- Kubernetes version: (use `kubectl version`): v1.22.10-eks
- OS (e.g. from `/etc/os-release`): Bottlerocket OS 1.9.1

**Comment by luthermonson** [comment]
just because i looked into this for like 10min ill leave some notes. 

in the go aws sdk for eks there is `CreateNodegroupInput` which has no support for volume types or anything that looks like the volume mapping you can do in ec2.

DiskType says this:
```
// The root device disk size (in GiB) for your node group instances. The default
// disk size is 20 GiB. If you specify launchTemplate, then don't specify diskSize,
// or the node group deployment will fail. For more information about using
// launch templates with Amazon EKS, see Launch template support (https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html)
// in the Amazon EKS User Guide.
```

It's possible we need to implement `CreateNodegroupInput.LaunchTemplate`? The way eksctl [got around](https://github.com/weaveworks/eksctl/pull/1016/files#diff-373ae168bb9dafd09335fca12b0ec6b8cdcc5a7d4ce4623b56a6ab9d2a995d6eR130-R137) this is by taking params and auto generating a launch config and assigning it on node group creation so perhaps CAPA should do the same thing. At bare minimum a user should be able to pass one in and use it.

**Comment by richardcase** [comment]
With #3094 (not released yet) this is possible via the launch template.

**Comment by richardcase** [comment]
As this is probably handled:

/priority awaiting-more-evidence
