### ISSUE TITLE
Ability to customize security group rules

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#392]
/kind feature

**Describe the solution you'd like**
#341 adds Calico rules to the security groups we apply to the cluster.
We also additionally include a bunch of "useful" defaults in the bootstrap cloudformation.

How do we manage the lifecycle of AWS resources which are critical to cluster operation but are being delivered by pluggable components?

Should we extend ProviderConfig for security rules?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Also wondering if the bundler @justinsb and others are working on include the concept of cloud resources?

cc @sethp-nr

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sethp-nr** [comment]
It's an interesting question, for sure. My interpretation of the landscape was that this project was a "reasonable default" implementation for a kubernetes cluster on AWS, which in my mind implied picking a CNI provider & wiring it up.

The other implementation strategy I considered was modifying the security group rules to allow "all traffic" between and within the controlplane and node SGs. IMO that's a different but still reasonable "default" spot to be, and it would leave the question of how to network largely up to the choices in the `addons.yaml` file.

**Comment by dlipovetsky** [comment]
Some notes:
There are two ways to allow end users to customize rules:
1. Modify rules in CAPA-reconciled security groups
2. Add security groups

Security groups are just collections of rules. An instance can have multiple security groups; AWS[ internally merges them all into one group](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html#security-group-rules), which is the most permissive of all the groups.

Currently, CAPA defines groups for specific machine roles (bastion host, control plane, node). The groups contain rules for the CNI plugin and stacked etcd. When an end users wants to use a CNI plugin other than Calico, or use external etcd, then those rules should not exist.

If CAPA can define groups for components, instead of machine roles, then it should be possible for the groups to contain only the necessary set of rules. That implies that end users are free to add security groups _with the guarantee that their groups will not break cluster functionality_ because of the way AWS' internal merge works.

I strongly prefer this to asking end users to modify CAPA-reconciled security groups. If end users are allowed to modify CAPA-reconciled security groups, CAPA itself will need to guarantee that end users are not breaking cluster functionality.

**Comment by detiber** [comment]
@dlipovetsky One potential downside to separating out everything into separate groups is that we could start running into AWS limits on the number of Security Groups that can be attached to an instance.

Based on the [docs](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html), it looks like we are limited to a maximum of 5 security groups per network interface, which means if we would exceed that, then we would have to start allocating multiple ENIs on instance creation as well as managing the security groups properly across the multiple ENIs.

**Comment by dlipovetsky** [comment]
@detiber Good point, thanks.

**Comment by dlipovetsky** [comment]
> To increase or decrease this limit, contact AWS Support. The maximum is 16. The limit for security groups per network interface multiplied by the limit for rules per security group cannot exceed 1000. For example, if you increase this limit to 10, we decrease the limit for your number of rules per security group to 100.

Per the docs linked, I want to note that while the default limit is 5 security groups per network interface, the limit can be increased on request, though there's no guarantee it would be.

End users should not have to request limit increases just to use CAPA's default security group configuration. But can end users be asked to request limit increases to be able to use CAP with custom security groups?

**Comment by dlipovetsky** [comment]
Another user story: Prometheus is a popular solution for monitoring. The Node Exporter is a popular way of collecting host-level metrics for Prometheus. Frequently, Prometheus "scrapes" (queries) Node Exporter endpoints. One Node Exporter runs on every host, and it runs in the host's network namespace. Therefore Node Exporter serves metrics on the host's IP, on some unprivileged port (typically 9100). 

With the default security group rules, a Prometheus Pod running on one host cannot reach a Node Exporter running in a different host.

I'm reaching out to the Prometheus folks to understand the consequence of running Node Exporter in the Pod network namespace and will report back here.

**Comment by benmoss** [comment]
This is a pain for us trying to add Windows support, since Calico only supports Windows with their "premium" product from Tigera. The main OSS CNI with good Windows support is Flannel, so we're stuck [documenting](https://github.com/benmoss/kubeadm-windows/tree/master/cluster-api-aws#adding-a-windows-node-to-your-aws-cluster-api-cluster) how to create SGs manually. This will also likely break cluster deletion, since you won't be able to delete the VPC when security groups still exist inside of it. It feels like if CAPA is going to create any SGs it should be possible to control what they are.

I'd be interested in working on adding support for this but it's not clear what the API would look like.

**Comment by Promaethius** [comment]
@randomvariable I'd like to pick this up

**Comment by randomvariable** [comment]
/unassign

design is needed.

**Comment by sedefsavas** [comment]
[CNIIngressRules field](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/461ef72c3b647e729298ec5507c3387dabf7b015/api/v1beta1/network_types.go#L337) will be deprecated.

This feature will solve https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1503

**Comment by bsideup** [comment]
@sedefsavas thanks for sharing! Are there any short term plans to implement this issue then? e.g. by accepting https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2876 ?

**Comment by sedefsavas** [comment]
Another customization to cover under this:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3314

**Comment by richardcase** [comment]
@belgaied2 - i think we can use this issue for our discussion. Would you be able to add your use case here?

**Comment by belgaied2** [comment]
Thanks @richardcase ,

Yes, this issue is of interest to us over at [cluster-api-provider-rke2](https://github.com/rancher-sandbox/cluster-api-provider-rke2) since RKE2 relies on node registration mechanism that uses a custom port on control plane machines.

Principle is as follows:
- First control plane machine initializes a cluster and open the port `9345`.
- subsequent nodes (both control plane and workers) will connect to that port to register themselves in the cluster.

This means that, if our provider needs to integrate with CAPA, it needs to customize the securityGroup for the controlplane (which is created by CAPA).

The reason why the existing feature of `additionalSecurityGroups` on `AWSMachineTemplate` resources does not work is because these securityGroup(s) need to exist beforehand, when the VPC is not yet created by the `AWSCluster` controller.

So, at best, we need a way to add a `securityRule` to the securityGroups that created by CAPA.

**Comment by richardcase** [comment]
This seems reasonable to me. I can work on this:

/assign
/lifecycle active

**Comment by cablunar** [comment]
@richardcase is there any ETA on the implementation? 🙏

**Comment by alexander-demicev** [comment]
@cablunar already working on it

**Comment by com6056** [comment]
Should this be closed if https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3271 still hasn't been addressed from what I can tell?
