### ISSUE TITLE
ExternalResourceGC feature flag needs to fall back when ResourceTagging API is unavailable (e.g. 'airgapped installs')

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#3987]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

AWS have not launched a VPC endpoint for the ResourceTagging API, as such the ExternalResourceGC does not work when there is no egress to the public internet, since when the API is unavailable, reconciliation fails entirely.

For the control plane loadbalancer, there is fall back code to enumerate all LBs and compare their properties. It is likely that this needs to be implemented in this case to make the feature usable in airgapped environments.

**What did you expect to happen:**

Cluster deletion continues.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by dlipovetsky** [comment]
/triage accepted
/priority important-longterm

> For the control plane loadbalancer, there is fall back code to enumerate all LBs and compare their properties. It is likely that this needs to be implemented in this case to make the feature usable in airgapped environments.

We may be able to support a External GC "strategy" that doesn't use the resource tagging API.

**Comment by dlipovetsky** [comment]
This is a dupe of #3668, but has a good description. I'll ask the author of #3668 if we should keep that one, or close it.

**Comment by dlipovetsky** [comment]
A fall-back mechanism might be more practical than asking the user to select the right "strategy." It's not easy for the user to know ahead of time if the resource tagging API will be reachable.

**Comment by randomvariable** [comment]
Ah, thanks. Happy to fold either way.

**Comment by richardcase** [comment]
I think we should refactor the code so that when you start CAPA with GC enabled you can change the gc "strategy" that is used. 

So we'd need a GC strategy interface and the existing resource tagging implementation refactored into an implementation of this as a GC strategy (i.e. implement the interface). Then a new strategy could be implemented that just queries (list/describe) the various AWS APIs directly for things like ALB/ELBS etc and then deletes them.

The existing strategy should be the default but the user can change to another strategy via a flag.

We have previously used the strategy pattern: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/b070107cfca830db0fe1c1c052310132e3980c86/pkg/cloud/scope/shared.go#L60 but not with a flag to change it.

**Comment by wyike** [comment]
Hi @richardcase @dlipovetsky  cc @randomvariable 

I prepared two draft commits:

fallback mechanism: https://github.com/kubernetes-sigs/cluster-api-provider-aws/compare/main...wyike:cluster-api-provider-aws:gc_fallback?expand=1
refactor with a gc strategy interface mechanism: https://github.com/kubernetes-sigs/cluster-api-provider-aws/compare/main...wyike:cluster-api-provider-aws:gc_refactor?expand=1

Functions of these two mechanisms are actually similar, just the whole code structure looks different. I have some feelings:
1. fallback mechanism is indeed more practical for users as they don't have too much knowledge of the environment. If we expose flag to let user or up-level cluster operator to set explicitly, it gives extra burden and work to them.
2. gc strategy interface mechanism changes the existing code structure a lot and it may classify different functions more clear. But so far I didn't see extra benefit compared with the big code structure change.
3. if we adopt gc strategy interface mechanism, it will be difficult to fallback from use default strategy (tagging client)to another strategy internally because gcService is initialized to use tagging or not at the very beginning. i.e. gc strategy interface mechanism must rely on user self setting to decide the strategy.

Could you help review the code changes and share your ideas? So that we can make a decision and continue the work in deep. Thanks!

**Comment by dlipovetsky** [comment]
@wyike, I'm sorry, I missed your [comment](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3987#issuecomment-1435513103) before.

I agree with your approach here. Offering more than one strategy is reasonable, especially since the external GC is still behind a feature flag.

I hope we can find one strategy acceptable for all use cases by the time we want to enable external GC by default.
