### ISSUE TITLE
Add machine actuator support for control plane join

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#413]
/kind feature

**Describe the solution you'd like**

The machine actuator should support joining additional control plane instances.

Depends on #412

**Comment by chuckha** [comment]
This will have to happen outside the context of `clusterctl` then? `clusterctl` always assumes a single master.

**Comment by chuckha** [comment]
Using phases this will work fine.

My approach would be: if it's got the `set: controlplane` label and you've successfully fetched a kubeconfig, that means the first instance is up and you'll want to do a join --control-plane-node. Otherwise it's the first instance of a controlplane node and you'll want to do an init.

Will require adding another userdata script.

Good luck to the brave adventurer that takes this ticket!

**Comment by ashish-amarnath** [comment]
@chuckha I was feeling rather brave to sign-up for this despite your cautionary comment :-)
Will be working at a slow pace over the break.

**Comment by ashish-amarnath** [comment]
Here is my proposal:
Maintain a count of the number of control plane nodes for the cluster. This count would be incremented/decremented on addition/removal of a control plane node.
This counter can also be used to prevent scenarios where it is possible to delete the only control plane node for a cluster, without deleting the cluster. (I know there is an issue for this not finding it atm, will link here once I do)
The implementation for this would look something like this:

1. Create a new type, `ClusterControlPlaneStatus` which, for now, will have just one field `ControlPlaneNodeCount`
```
type ClusterControlPlaneStatus struct {
    ControlPlaneNodeCount int `json:"controlPlaneNodeCount`
}
```
2. Include a field of type `ClusterControlPlaneStatus` in `AWSClusterProviderStatus`
3. Make the machine actuator `Create` and `Delete` functions to update the `ClusterControlPlaneStatus` accordingly.

I'll update the PR following this approach.

**Comment by chuckha** [comment]
I'm a little bit confused about the ClusterControlPlaneStatus proposal. Why do we need the counter for creating new control planes? I was thinking the existence of the kubeconfig would be enough to know if we are doing a control plane --join vs a control plane --init.

Solving the deletion problem is a totally different beast. We haven't quite agreed about how that will work, but having more input would be great! Please add comments to this issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/215.

**Comment by ashish-amarnath** [comment]
So I tried `kubeconfig, err := a.GetKubeConfig` and if `err == nil` then taking the `--join` path and `--init` path if otherwise.
Taking a closer look at `GetKubeConfig` method… I don’t see anything that tests a controlplane node has been created…`GetKubeConfig` succeeds if the loadbalancer for the cluster has been reconciled.

**Comment by chuckha** [comment]
Follow this discussion https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/463#discussion_r246430304 the spec is going to change to add CAs and service account keypairs.

**Comment by ashish-amarnath** [comment]
created https://github.com/kubernetes-sigs/cluster-api/issues/682 to support bootstrapping clusters with multiple masters. https://github.com/kubernetes-sigs/cluster-api/issues/682
To support this scenario we'll have to make `isNodeJoin` method in the machine acuator thread safe.
