### ISSUE TITLE
Pass context from Reconcile functions to AWS requests

### ISSUE THREAD

**Issue by Fedosin** [kubernetes-sigs/cluster-api-provider-aws#4504]
/kind feature

**Describe the solution you'd like**
Currently we do not transfer the Context further at the time of reconciliation. This makes it difficult to map Reconcile function calls to requests to AWS, which limits our ability to monitor the operation of CAPA in runtime.

It would be nice to to pass through Context top-down, so we can use it in OpenTelemetry to generate more detailed traces.

Working items:
- [ ] Migrate AWS Reconcile function calls to their WithContext equivalents (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4490)
- [ ] Change `context.TODO()` values to real contexts.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by nrb** [comment]
Thanks for opening the issue!

Would you mind adding a checklist of the work items you're thinking of?

Reading the PR, might I suggest

[ ] Migrate AWS Reconcile function calls to their WithContext equivalents (#4490)
[ ] Change `context.TODO()` values to real contexts.

I think the 2nd one might be split up, though I'm not sure what axis makes most sense - it could be done per package or by call chain. By call chain's probably more useful, since per-package doesn't actually plumb the context end-to-end by definition.

**Comment by Fedosin** [comment]
@nrb Thanks! That's probably it. My initial plan implement it as a part of OpenTelemetry adoption initiative, but probably it's better to separate them. In this case your two items is enough.
