### ISSUE TITLE
Clean up of AWS resources doesn't happen upon create cluster failure

### ISSUE THREAD

**Issue by babu-selector** [kubernetes-sigs/cluster-api-provider-aws#471]
/kind bug

**What steps did you take and what happened:**
Please see issue #470 for initial steps.

Upon failure, the AWS resources still exists.

![screen shot 2019-01-05 at 2 32 49 pm](https://user-images.githubusercontent.com/44914817/50729916-224dc780-10f7-11e9-99ef-a2ba659e4d41.png)

**What did you expect to happen:**
AWS resources to be cleaned up. If it has to be explicitly deleted then mention the steps in the startup guide.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
After a little debugging on this issue, I can say that as of right now this is expected behavior. Clusterctl won't go and delete resources that have been created upon failure. 

You can try to use `clusterctl delete cluster ...` to delete resources, but if those are orphaned users are expected to delete them manually. This behavior is also present in other infrastructure management tools like CloudFormation or Terraform.

I'm going to close this issue, we should probably bring this upstream for the next iteration. Feel free to reopen if I missed anything.

/close
