### ISSUE TITLE
Bootstrap cluster should use STS Session tokens

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#496]
/kind feature

**Describe the solution you'd like**
In the current behavior, when a user runs `clusterawsadm` the environment credentials are used to create the CloudFormation template and to generate an aws profile configuration file which is then used as a secret. 

For a bootstrap (short-lived) cluster, we should generate a session token using [sts api](https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#GetSessionTokenInput). The session token is usually short lived and should be enough to guarantee successful operations until pivot.

After pivoting, the cluster should default to use IAM roles or static credentials, giving users a way to pick what's best for their use case.

**Comment by randomvariable** [comment]
This has been discussed on Slack, but we purposely do not do STS calls as this will prevent clusterawsadm being used in environments where the user has either had to already assume a role to access the AWS account using cross-account IAM roles, or is working in an environment where access is granted using federated identity.

Either a `--no-session` parameter would need to be added to avoid this behaviour, or we do nothing and recommend users use a tool such as `aws-vault` to provide temporary sessions when they are using static AWS access keys.

**Comment by chuckha** [comment]
@rosskukulinski

**Comment by rosskukulinski** [comment]
@chuckha / @randomvariable I don't have quite enough context to weigh in just yet.  @randomvariable can you point me to the Slack discussions you reference?  IIRC, the Heptio-alum AWS accounts are setup where people must assume roles to access regions, right?

@vincepri - What are the failure conditions should the bootstrap cluster not come up before STS token expires?  What duration were you thinking about using?

**Comment by randomvariable** [comment]
I'll need to find the Slack conversations, but this is the current state as I see it:

## Current State

### CloudFormation

`clusterawsadm alpha bootstrap create-stack` creates an AWS CloudFormation stack with the following resources:

#### IAM Managed Policies
* `nodes.cluster-api-provider-aws.sigs.k8s.io`

This is a misnomer, as it should be `nodes.cluster-provider-aws.k8s.io`, and is the per-node IAM policy as used by the AWS Cloud Provider for Kubernetes (issue to follow).

* `control-plane.cluster-api-provider-aws.sigs.k8s.io`

This is a misnomer, as it should be `control-plane.cluster-provider-aws.k8s.io`, and is the per-node IAM policy as used by the master nodes for the AWS Cloud Provider for Kubernetes (issue to follow).

* `controllers.cluster-api-provider-aws.sigs.k8s.io`

This is the IAM policy that grants permissions to the
controller to do all the necessary actions within a single
account. Any calls to AWS SDK within the actuators should
also be added here with the minimal permissions required for use.

#### IAM Roles

##### `control-plane.cluster-api-provider-aws.sigs.k8s.io`

This role has attached to it the following policies:
* `nodes.cluster-api-provider-aws.sigs.k8s.io`
* `control-plane.cluster-api-provider-aws.sigs.k8s.io`
* `controllers.cluster-api-provider-aws.sigs.k8s.io`

This is intended for the use case of instances running a
Kubernetes control plane as well as the controllers for
the cluster.

##### `nodes.cluster-api-provider-aws.sigs.k8s.io`

This role has attached to it the following policy:
* `nodes.cluster-api-provider-aws.sigs.k8s.io`

This is intended for all nodes which are not part of
the control plane, and has limited access in order
to make the AWS Cloud Provider functional.

##### `controllers.cluster-api-provider-aws.sigs.k8s.io`

This role has attached to it the following policy:
* `controllers.cluster-api-provider-aws.sigs.k8s.io`

This is intended for the use case where AWS credentials
are given to the controllers by means other than the
control plane node's EC2 instance profile credentials.

Typically, this would be kiam or another AWS metadata
proxy service.

The other purpose for this is for test suites to assume
this role and ensure the CloudFormation policies are
accurate during integration testing.

All three roles have trust policies for `ec2.amazonaws.com` to assume role that role during
EC2 boot.

#### IAM Instance Profiles

We create three instance profiles, with the same name
as each of the IAM roles.

The intention is that by default, these are attached to
the created EC2 instances as follows:

* All control plane nodes:
  `control-plane.cluster-api-provider-aws.sigs.k8s.io`
* All other nodes:
  `nodes.cluster-api-provider-aws.sigs.k8s.io`

#### IAM Users

We also create the following IAM Group and User:

##### `bootstrapper.cluster-api-provider-aws.sigs.k8s.io`

which has the following IAM policy attached:

* `controllers.cluster-api-provider-aws.sigs.k8s.io`

## Bootstrap process and desired state

When creating a cluster using `clusterctl` on the command
line, the above IAM user is currently the best way for a
end-user to inject credentials into the bootstrap control plane provided by Minikube or KIND.

Rught now, shell commands are provided which run `clusterawsadm alpha bootstrap generate-aws-default-profile` to create a Kubernetes
secret which is then injected into the provider components manifest.

This is because currently, `clusterctl` pivots all Cluster API controller resources to the target cluster.

However, we have already created IAM policies, IAM roles and instance profiles such that we do not need to pivot
these credentials at all - the controllers will be able
to perform EC2 instance metadata lookups and retrieve the
AWS session tokens for the relevant IAM instance profile,
and which that has all permissions listed under
the `controllers.cluster-api-provider-aws.sigs.k8s.io` IAM
policy.

Three things are needed:
* The secret not to be pivoted
    * https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/201
    * https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/297
    * https://github.com/kubernetes-sigs/cluster-api/issues/556
* The controller pod manifest to not reference the secret
  so it can start up.
* Delete the IAM keys for the bootstrap user as they
  will no longer be needed after pivot.

### Concerns for other modes of running

#### Controller clusters

Controller clusters will be typically running already in
AWS, and not go through the process of `clusterctl`. It
might be that `clusterctl` has created this controller
cluster.

There will be two modes of running that the controller
will need to consider:

##### Managing clusters in the same AWS account

When a controller cluster is running in the same account
as target clusters, the controller should use the
`controllers.cluster-api-provider-aws.sigs.k8s.io` IAM
role, given to it either through an EC2 instance profile
attachment, or via KIAM or suitable metadata proxy.

##### Managing clusters across AWS accounts

When managing clusters across AWS accounts, the role
or instance profile for the controller will need additional IAM permissions to assume roles in those accounts, like:

```
{
  "Version": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Action": "sts:AssumeRole",
    "Resource": "arn:aws:iam::TARGET-ACCOUNT-ID:role/controllers.cluster-api-provider-aws.sigs.k8s.io"
  }
}
```

In addition, the role in the target account will need
trust policy statements to allow role assumption from the
controller cluster account.

There is sufficient complexity here that automating this
via `clusterawsadm` is currently out-of-scope, and should
be considered the problem of higher-level tooling.

It is however, likely that the cluster and/or machine
provider spec will need to be extended to

#### End-users

##### Typical cross-account access set up

AWS Well-Architected and Enterprise ProServ recommend the
use of a central IAM account, with access to other
accounts given via IAM cross-account role assumption.

This will normally involve the use of `sts:AssumeRole`.

After this, the user will not be able to perform role
assumption again in the account that they've got access
to. This means a workflow cannot be given where `sts:AssumeRole` is always run in the controller.

### SDK best practices

When using AWS services via standard SDKs, a standard
authentication chain is followed in order to get a
set of credentials. This is in descending order:

1. Explicit credentials
   * This is when an SDK call is made, explicitly
     providing AWS credentials - access key ID, secret
     access key, and (optional) a session token.
2. Environment variables
  * If no credentials are given explicitly, the SDKs will
    check the running process'es environment variables for
    `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`

3. Default credential profiles file
  * The default profile from `~/.aws/credentials` will be
    loaded.

    Early versions of the `clusterctl` workflow used this
    mechanism to inject credentials into minikube via SSH
    and then do a volume mount to  `/root/.aws` inside
    Minikube. After pivot to the cluster, there would be
    no such directory, and the SDK would not find
    credentials here and continue falling down the credential chain. In addition, the relevant
    directory on the minikube host was `tmpfs` mounted so would be unlikely to leave a trace of the credentials
    on the host disk.

    This was eschewed as it led to user confusion,
    and would also not be compatible with KIND at all,
    or would require completely different manifests for
    controller clusters, in favour of the explicitly mapping a Kubernetes secret in the provider components manifests with credentials taken from the
    user's environment, which does get pivoted. This means if the user does not change their environment variables to be the bootstrapper user above, they will leak these creds into the target cluster.

    The docs therefore recommend the use of
    [`aws-vault`](https://github.com/99designs/aws-vault),
    which will provide time-limited session credentials,
    without the controller having to make any assumptions
    as to how credentials are sourced.

4. Amazon ECS container credentials

   If the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` env var
   is present, then it is checked to then retrieve
   credentials from a metadata proxy service running on
   the host. This method was intended to be part of
   [KEP 14](https://github.com/kubernetes/community/pull/2329/files),
   but it is expected a new OIDC mechanism will be added to the SDKs to integate with Kubernetes more thoroughly.

1. Instance profile credentials

   The SDK as a last resort will curl the instance metadata URL and look for instance profile credentials.

   Metadata proxy services such as
   [kiam](https://github.com/uswitch/kiam) and
   [kube2iam](https://github.com/jtblin/kube2iam)
   imitate this to provide per-pod IAM roles, and will
   be the current mechanism by which to ideally provide
   credentials to the CAPA controllers in production
   environments.

### Implications

The SDKs go down this chain and the first provider wins.
This means that adding specific login logic to controllers
will preclude the use of instance profiles and metadata
proxy providers which are the current best practice.

Adding specific login logic to end-user workflows will
preclude the use of tools such as [AWS Vault](https://github.com/99designs/aws-vault),
[aws-assume-role](https://github.com/scalefactory/aws-assume-role),
as well as the custom enterprise-level
OIDC and LDAP authenticators.

Therefore, my recommendation is not to encode any
particular use case in code such that it precludes
another, and enforcing best practice is a concern for
end-users and higher-level tooling.

**Comment by randomvariable** [comment]
Going to write a version of the above for #519, which is why it's at length.

**Comment by randomvariable** [comment]
We've proven this works now, so closing.

/close
