### ISSUE TITLE
investigate what happens when a machine with a duplicate name of an existing machine is created in a different namespace

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#808]
/kind bug

I think this is a bug and this issue is mostly here to remind me to look into this at some point and flesh out the actual bug details or close if it's not an issue.

When two machines share a name but not a namespace, does everything still work as expected?

**Comment by detiber** [comment]
I don't expect there to be issues as long as they do not also share the same "cluster" name. That said, we currently do not prevent multiple "clusters" existing in different namespaces, however that would definitely cause issues today.

**Comment by ashish-amarnath** [comment]
This will be a problem based on how we, currently, look if a machine exists. Specifically, when we look for instances by tags. https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.3/pkg/cloud/aws/services/ec2/instances.go#L66
Even more specifically, that problem is 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.3/pkg/cloud/aws/services/ec2/instances.go#L86-L88
This will not be an issue if the machines belong to a different cluster (and therefore a different VPC?).

**Comment by ncdc** [comment]
I'm curious why we need to query for an instance by tags if we have instance ID?

**Comment by ashish-amarnath** [comment]
We query by tags only when we don't find the instanceID
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.3/pkg/cloud/aws/services/ec2/instances.go#L481

But when there is a naming conflict, I think, we'll end up w/ 2 machine objects being liked to the same instance ID.

**Comment by ncdc** [comment]
Right, but _why_? 😄 

IMHO, if a `Machine` does not have `spec.providerID`, we must do a `create` operation. If it does have `spec.providerID`, then we should be doing existence/health checks and setting the error state appropriately if the VM is not pending or running (+ maybe shutting down & stopped too).

**Comment by detiber** [comment]
@ncdc The reason for the check is in case we create the instance but we are not able to update the Machine object for some reason.

**Comment by ncdc** [comment]
Ok, that's fair.

**Comment by MarcusNoble** [comment]
#969 seems to answer this question, is this issue still relevant?

**Comment by randomvariable** [comment]
thanks @MarcusNoble .

/close
since that one supersedes.

Going to take to SIG Cloud Provider for further discussion.
