### ISSUE TITLE
Failure in cluster deletion [unable to remove finalizer from cluster CRD]

### ISSUE THREAD

**Issue by vivgoyal** [kubernetes-sigs/cluster-api-provider-aws#891]
/kind bug

**What steps did you take and what happened:**
Deletion of cluster sometimes gets stuck in a state in which it is unable to remove finalizer from the cluster CRD. It gets into an endless loop.
Error: cluster_controller.go:133] Error removing finalizer from cluster object cl-34bbaad7; Operation cannot be fulfilled on clusters.cluster.k8s.io "cl-34bbaad7": the object has been modified; please apply your changes to the latest version and try again

**What did you expect to happen:**
I expect the deletion logic to finish successfully on retry.

**Anything else you would like to add:**
This is not a one-off. Have seen this happening many times.

**Environment:**

- Cluster-api-provider-aws version: 0.3.1
- Kubernetes version: (use `kubectl version`): 1.14.1

**Comment by ncdc** [comment]
I do know that in the cluster actuator's Delete() call, it will update the cluster, which gives it a new resourceVersion. Once the Delete() call returns successfully, the CAPI cluster controller then tries to update the cluster to remove the finalizer. This fails with the conflict error you've shown above. It should retry and eventually succeed, but it would be nicer to re-get the cluster after the actuator Delete() is done and before trying to remove the finalizer. If we pursue that for the fix, it belongs in CAPI release-0.1.

**Comment by ncdc** [comment]
@vivgoyal I have only been able to reproduce this once. Do you have a set of steps the reproduce this consistently for you?

**Comment by vivgoyal** [comment]
@ncdc this is not reproduced any differently. It happens every once in a while for the same set of steps that I run.

**Comment by ncdc** [comment]
@vivgoyal can you share those steps?

**Comment by ncdc** [comment]
I am fairly confident this is the root cause of the issue:

1. During the initial cluster reconcile loop iteration, CAPA creates the ELB for the cluster, but it's not ready yet, and we set cluster.status.apiEndpoints[0].host to `""` (the empty string).
1. During each subsequent cluster reconcile loop iteration, we infinitely append the correct host as a new endpoint to the cluster.status.apiEndpoints array
1. When you issue a delete, this same infinite appending occurs in the CAPA cluster actuator
1. This change results in a new cluster.metadata.resourceVersion
1. The CAPI cluster controller has a stale copy of the cluster - its resourceVersion is from before CAPA added another apiEndpoint
1. The CAPI cluster controller tries to remove the finalizers by performing an Update operation, which requires the latest resource version
1. Because it's not the latest resource version, the update fails with `the object has been modified; please apply your changes to the latest version and try again`

Fortunately, the infinite appending bug was fixed in #881 for master, #887 for release-0.3, and is in v0.3.4.

There is still a change we should make in CAPI - we should use patch to remove the finalizers instead of update. We're already doing that in master for v1alpha2 work, but I'll do a PR to fix this for CAPI release-0.1.

**Comment by ncdc** [comment]
The CAPI fix merged and has been incorporated into CAPA v0.3.6.
/close
