### ISSUE TITLE
user story: use CAPA to create a mamanger cluster which is for deploy user Cluster

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#980]
/kind feature

create a CAPA cluster by CAPA Cluster

1:  create a bootstrap cluster by CAPA ( provider is kind
2: deploy provider-components to bootstrap cluster
3: create a cluster by the controller which run in the bootstrap cluster

and I find the document about this
 
```
1. Creating a management cluster in AWS - This can be done by running the phases in clusterctl
    * Uses the existing provider components yaml
2. Setting up cross account IAM roles
3. Deploying the KIAM server/agent
4. Create the target cluster (through KIAM)
    * Uses different provider components with no secrets and annotation to indicate the IAM Role to assume.

```

**Comment by ncdc** [comment]
If you create a cluster in AWS, either with `clusterctl create cluster`, or by manually performing similar steps (create a kind bootstrap cluster, deploy CAPA, create a `Cluster` and `Machines`, etc), you end up with a cluster that can act as a management cluster. The `clusterctl` approach makes this pretty easy, since it pivots. Could you please clarify what you're looking for?

**Comment by Sn0rt** [comment]
> If you create a cluster in AWS, either with `clusterctl create cluster`, or by manually performing similar steps (create a kind bootstrap cluster, deploy CAPA, create a `Cluster` and `Machines`, etc), you end up with a cluster that can act as a management cluster. The `clusterctl` approach makes this pretty easy, since it pivots. Could you please clarify what you're looking for?

this is it.
